### ISSUE TITLE
Support for schema 2020v4.2?

### ISSUE THREAD

**Issue by gtl-alex** [jsfenfen/990-xml-reader#33]
The latest XML filings released by the IRS include 990s with schema version **2020v4.2**. Are there plans to add support for this version? 

Btw, thank you for this great project! It's been extremely helpful.

**Comment by jsfenfen** [comment]
This version has been allowed in [version 0.3.3](https://pypi.org/project/irsx/) ( `$ pip install irsx --upgrade` ) in the settings.py file, but the metadata has not yet been updated to include new xpaths introduced in version year 2020 or since then. I hope to do this at some point in the future. This change should allow irsx to run on this version, perhaps with errors. You can follow along the progress in adding new metadata in #36
