### ISSUE TITLE
Support for new data 2021, 2022

### ISSUE THREAD

**Issue by vishalavalani** [jsfenfen/990-xml-reader#35]
First of all thanks a lot for this irsx, it is indeed very helpful.

Do we have tentative timeline when it will support 2021 and 2022 data which is released now?
(Ref link: https://apps.irs.gov/pub/epostcard/990/xml/2022/2022_TEOS_XML_01A.zip)

It is giving errors:
Ref:
Filing version 2021v4.2 isn't supported for this operation
Filing version 2021v4.1 isn't supported for this operation
Filing version 2021v4.0 isn't supported for this operation
Filing version 2021v4.2 isn't supported for this operation

Request you to look into the issue and provide an update.

Thanks,
Vishal

**Comment by aravindk777** [comment]
I have the same question/concern.

**Comment by jsfenfen** [comment]
These versions have been allowed in [version 0.3.3](https://pypi.org/project/irsx/) ( `$ pip install irsx --upgrade` ) in the settings.py file, but the metadata has not yet been updated to include new xpaths introduced in version year 2020 or since then. I hope to do this at some point in the future. This change should allow irsx to run on these versions, perhaps with errors. You can follow along the progress in adding new metadata in #36
